### PR TITLE
Issues/185/3.7

### PR DESCRIPTION
**Pull request by IshentRas**
Ok not too much for 3.7

### CODE REVIEW

**Comment by IshentRas** [comment]
@ianmiell @jperville I included the docker CHEF deps so as to run native chef commands instead of 'execute' commands.
Let me know if you are ok with that

**Comment by ianmiell** [comment]
I agree - would prefer to use native Chef where possible. I'll look at getting the package installed within $work. We are still on 3.3 so we have time to adjust.

**Comment by ianmiell** [comment]
I'll run the tests for 3.7 asap.

**Comment by jperville** [comment]
@IshentRas agree with using chef docker cookbook (very nice cookbook, to which I submitted quite a few PRs in the early days).

If using this cookbook we should rewrite the code in recipes/common.rb that installs and configures docker. We should be using the LWRPs from the docker cookbook instead of installing and configuring the package on our own; this would allow me to stop abusing the `node['cookbook-openshift3]['docker_log_options']` attribute to pass custom options to the docker daemon such as insecure registries etc.

**Comment by ianmiell** [comment]
Passes:
http://jenkins.meirionconsulting.tk/job/cookbook-openshift3/job/issues%252F185%252F3.7/

**Comment by ianmiell** [comment]
Test suite updated to pull and apply docker module.

**Pull request merged**
