### PR TITLE
[DO NOT MERGE] WIP OSE v3.10 support

### PR DESCRIPTION
**Pull request by jperville**
Hello everyone,

This PR is my first attempt at extending this cookbook to support deploying OSE v3.10 (see #256). It does not include major version upgrade from v3.9 to v3.10 and I am not sure how correct the templates and configuration files are. Finally, the kitchen tests all pass.

My (maybe incorrect) impression is that the configuration of OSE v3.10 is very to v3.9 (identical scheduler predicates policies  etc) and that very little work needs to be done to have proper support for OSE v3.10.

What the PR does:
 - deploy OSE v3.10 in cluster native mode
 - pass the standard kitchen tests

What is still to do:
 - check that master-config.yml, node-config.yml are correct (by default I used same as v3.9 version)
 - add proper templates for OSE 3.10 logging and metrics (if any different than v3.9 version)
 - handle major version upgrade from v3.9 to v3.10 (ping @IshentRas )
 - add Jenkinsfile from OSE 310 (ping @ianmiell)

Hacks/Gotchas:
 - I had to force the yum repository (in attributes/default.rb) to http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin because OSE 3.10 packages depend on openvswitch >= 2.6.1, which is not present in http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin310 (this is probably a bug). I don't like the shared yum repository because a simple "yum upgrade" can install a new version of packages without following the proper upgrade procedure.

### CODE REVIEW

**Comment by IshentRas** [comment]
Thanks for the work. I'll rebase on your branch and chekc

**Comment by jperville** [comment]
Thanks @IshentRas . To get started, have a look at the attributes that I set in https://github.com/PerfectMemory/cookbook-openshift3/blob/wip-ose-v310/test/roles/openshift3-base-ose310.json

**Comment by IshentRas** [comment]
@jperville I need more time. Actually thinking of revamping the cookbook for 3.10+
Indeed, a lot of things have changed and it is an opportunity to create a separate config for 3.10+
I have not decided yet which way I am going to take but I need a bit more time to test everything. I should be ready by next week.
I am going to use your first draft and add more commit as I progress.

**Comment by jperville** [comment]
@IshentRas I rebased this PR over current PR. I think we now have robust support for OSE v3.9 and can start working on OSE v3.10, Feel free to add commits to this PR as you progress.

**Comment by IshentRas** [comment]
@jperville Thanks again for this PR. Unfortunately, I have decided to rewrite the logic for 3.10+ and therefore I won't use what you have done. At least not all.
The new version brings lots of changes and it makes sense to revamp the cookbook for version >= 3.10.
I am currently writing the logic and I should be able to push something by next middle of next week.
Thanks for your understanding and contribution :+1:

**Pull request closed without merging**
