### PR TITLE
OSE v39 kitchen tests

### PR DESCRIPTION
**Pull request by jperville**
This PR contains multiple commits which fix and extend the current kitchen tests to:
 - test deployment of OSE v3.9 in cluster native mode
 - fix deployment of OSE v3.6 and v1.5 logging in standalone and cluster native mode
 - test the newly added openshift_hosted_cluster_logging feature for all supported versions
 - update README.md so that the listed supported versions match what is actually tested

I ran the kitchen tests for every supported version with chef-dk 3.10 (my old version 1.16 had a bug where it would exit non-zero but display "no errors" when actually the permission tests for /etc/origin/* were failing).

```sh
jp440p:cookbook-openshift3(9m|ose-v39-kitchen-tests?) $ kitchen list
Instance                        Driver   Provisioner  Verifier  Transport  Last Action  Last Error
cluster-native-ose39-centos-74  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
cluster-native-ose37-centos-74  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
standalone-ose36-centos-74      Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
cluster-native-ose36-centos-74  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
standalone-ose15-centos-74      Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
cluster-native-ose15-centos-74  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
```

### CODE REVIEW

**Comment by ianmiell** [comment]
Please note the automated tests are down at the moment (my personal 'data
centre' is down while we have our house redecorated), but should be back up
in the coming days.
Ian

**Comment by jperville** [comment]
@IshentRas please do NOT merge this before I rebase master (you merged #261 early!).

**Comment by jperville** [comment]
PR rebased to current master, safe to merge.

**Comment by jperville** [comment]
@IshentRas I will now work on OSE v3.10 support, thanks for merging everything.

**Pull request merged**
