### PR TITLE
More cookstyle fixes

### PR DESCRIPTION
**Pull request by jperville**
A trivial PR to make the `cookstyle` tool happy.

### CODE REVIEW

**Comment by IshentRas** [comment]
@jperville I undo that part as we were not passing rubocop checks because of extra comma... Need to check why you are failing that part

**Comment by IshentRas** [comment]
# rubocop -r cookstyle -D --format offenses

--
0  Total

# cookstyle -D --format offenses

--
0  Total

**Comment by jperville** [comment]
Which version of chef-dk/cookstyle are you using?

```sh
jp440p:cookbook-openshift3(70m|master) $ cookstyle -D --format offenses

2  Style/TrailingCommaInLiteral
--
2  Total

jp440p:cookbook-openshift3(70m|master) $ cookstyle --version
Cookstyle 1.1.0
  * RuboCop 0.46.0
```

**Comment by IshentRas** [comment]
lol Fair enough lol

[wburton@pc-wburton cookbook-openshift3]$ /home/wburton/bin/rubocop -r cookstyle 
Inspecting 57 files
........................C.C..............................

Offenses:

recipes/master.rb:74:9: C: Put a comma after the last item of a multiline hash.
        secret_encryption: Mixlib::ShellOut.new('/usr/bin/openssl rand -base64 24').run_command.stdout.strip
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes/etcd_cluster.rb:182:9: C: Put a comma after the last item of a multiline hash.
        initial_cluster_state: etcd_servers.find { |etcd_node| etcd_node['fqdn'] == node['fqdn'] }.key?('new_node') ? 'existing' : node['cookbook-openshift3']['etcd_initial_cluster_state']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

57 files inspected, 2 offenses detected
[wburton@pc-wburton cookbook-openshift3]$ vim recipes/master.rb recipes/etcd_cluster.rb 
2 files to edit

[1]+  Stopped                 vim recipes/master.rb recipes/etcd_cluster.rb
[wburton@pc-wburton cookbook-openshift3]$ fg
vim recipes/master.rb recipes/etcd_cluster.rb
[wburton@pc-wburton cookbook-openshift3]$ /home/wburton/bin/rubocop -r cookstyle 
Inspecting 57 files
.........................................................

57 files inspected, no offenses detected
[wburton@pc-wburton cookbook-openshift3]$

**Comment by IshentRas** [comment]
:+1:

**Comment by jperville** [comment]
Let's supply a rubocop.yml to make explicit formatting preferences such as this one.

**Pull request merged**
