### PR TITLE
Support Audit logging in Openshift v3

### PR DESCRIPTION
**Pull request by taylok**
This PR is to support audit logging in open shift v3: ref https://access.redhat.com/solutions/1748893

### CODE REVIEW

**Comment by ianmiell** [comment]
@IshentRas might disagree but I think I'd prefer if the item were always in the config, and true/false put in there as appropriate.

**Comment by IshentRas** [comment]
@ianmiell :+1: 
@taylok Can we please implement like that instead?

**Comment by IshentRas** [comment]
@taylok : I have just added the possibility. Can you please check you are happy by rebasing your work against the latest code.
https://github.com/IshentRas/cookbook-openshift3/commit/ce226b8b549f5e2ef768e24f44704e433f62a2ab

**Comment by taylok** [comment]
I have rebased mine against yours - hope it is OK.

**Comment by IshentRas** [comment]
@taylok @ianmiell  Will push a new version later of the cookbook asI need to include other stuff :+1:

**Pull request closed without merging**
